# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQTTExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MQTTExample
pod 'MQTTClient'

  target 'MQTTExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MQTTExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
